name: Lastfm album timeline

on:
  schedule:
    - cron: '18 19 * * *'
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.x'
        - name: Install dependencies
          run: python -m pip install --upgrade pip setuptools wheel pylast
        - name: Run main.py
          # valid timeframe values: 7day, 1month, 3month, 6month, 12month, overall
          run: python main.py -u "$LASTFM_USERNAME" --API_KEY "$LASTFM_API_KEY" --API_SECRET "$LASTFM_API_SECRET" -r 2 -c 5 -t 7day
          env:
            LASTFM_USERNAME: ${{ secrets.LASTFM_USERNAME }}
            LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
            LASTFM_API_SECRET: ${{ secrets.LASTFM_API_SECRET }}
        - name: Commit README.md
          uses: EndBug/add-and-commit@v9
          with:
            add: 'README.md'
            default_author: github_actions
            message: 'Action: Updated README.md.'
            push: origin main --force
